### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by abstractmagicalwand** [abstractmagicalwand/spellbook#1]
- [ ] Debugging
- [ ] FP
- [ ] Event Loop
- [ ] HTTP vs WebSocket
- [ ] [Data Structures](https://github.com/trekhleb/javascript-algorithms)
- [ ] Session storage vs local storage vs cookies vs indexedDB
- [ ] Flux
- [ ] Mutable vs Immutable
- [ ] REST vs GRAPHQL
- [ ] Redux vs Context API
- [ ] Canvas vs DOM vs SVG
- [ ] WebAuthn
